### ISSUE TITLE
请问执行sudo alien -r lantern-installer-64-bit.deb 报错是什么原因

### ISSUE THREAD

**Issue by recotone** [guoxiaoxu/install-lantern#1]
dpkg-deb (子进程)：无法从 lantern-installer-64-bit.deb 中拷贝归档成员到解码管道中：未预期的文件结束或流结束
dpkg-deb (子进程)：解压缩归档成员：lzma 错误：未预期的输入结束
dpkg-deb：错误：子进程 <解压缩> 返回错误状态 2
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now
Error executing "dpkg-deb --fsys-tarfile 'lantern-installer-64-bit.deb' | tar tf -":  at /usr/local/share/perl5/Alien/Package.pm line 481.

**Comment by guoxiaoxu** [comment]
你的系统不是Centos吧？这条命令是把dbd包转为rpm包。或者你的系统安装了dpkg-deb软件。如果是Ubuntu 直接解压安装就行了。没必要这么麻烦。 @recotone  没研究过Ubuntu的安装方式

**Comment by recotone** [comment]
不是的 @guoxiaoxu 我的系统就是centos7

**Comment by guoxiaoxu** [comment]
@recotone 你安装 apt-get 这个软件了么？有的话卸载掉。重新跑一遍应该可以的，
